"""Add task_assignments association table and relationships

Revision ID: 526fb8b28315
Revises: eb7e2c578f8a
Create Date: 2026-04-14 11:09:25.137385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526fb8b28315'
down_revision = 'eb7e2c578f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assignment',
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_assignment_task_id_tasks')),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], name=op.f('fk_task_assignment_volunteer_id_volunteers')),
    sa.PrimaryKeyConstraint('volunteer_id', 'task_id', name=op.f('pk_task_assignment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_assignment')
    # ### end Alembic commands ###
